defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"


[consul]
  watch = true
  prefix = "traefik"


[consulCatalog]
  domain = "localhost"
  prefix = "traefik-consul"


[web]
  address = ":8080"
