version: '3.7'

services:
  ####
  # Users Service
  ###############################################
  users:
    image: nest-playground/users
    restart: always
    environment:
      PORT: 4040
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    networks:
      - consul-net
    ports:
      - 4040:4040
